# -*- coding: utf-8 -*-
"""Finpro_BusTicketing_A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aDx-jKYbUdaXa3J4ppZeuwmPllNJJlix
"""

from prettytable import PrettyTable

table = PrettyTable(["NO.", "TANGGAL", "KEBERANGKATAN", "TUJUAN", "KELAS", "JAM"])
table.add_row(["1.", "JAKARTA", "1 - 7 JANUARI", "BANDUNG", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["2.", "JAKARTA", "8 - 15 FEBRUARI", "BANDUNG", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["3.", "JAKARTA", "16 - 23 MARET", "BANDUNG", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["4.", "JAKARTA", "24 - 30 APRIL", "BANDUNG", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["5.", "JAKARTA", "1 -7 JANUARI", "BANDUNG", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["6.", "JAKARTA", "8 - 15 FEBRUARI", "BANDUNG", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["7.", "JAKARTA", "16 - 23 MARET", "BANDUNG", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["8.", "JAKARTA", "24 - 30 APRIL", "BANDUNG", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["9.", "JAKARTA", "1 -7 JANUARI", "YOGYAKARTA", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["10.", "JAKARTA", "8 - 15 FEBRUARI", "YOGYAKARTA", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["11.", "JAKARTA", "16 - 23 MARET", "YOGYAKARTA", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["12.", "JAKARTA", "24 - 30 APRIL", "YOGYAKARTA", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["13.", "JAKARTA", "1 - 7 JANUARI", "YOGYAKARTA", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["13.", "JAKARTA", "8 - 15 FEBRUARI", "YOGYAKARTA", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["13.", "JAKARTA", "16 - 23 MARET", "YOGYAKARTA", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["16.", "JAKARTA", "24 - 30 APRIL", "YOGYAKARTA", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["14.", "JAKARTA", "1 - 7 JANUARI", "SEMARANG", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["14.", "JAKARTA", "8 - 15 FEBRUARI", "SEMARANG", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["14.", "JAKARTA", "16 - 23 MARET", "SEMARANG", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["14.", "JAKARTA", "24 - 30 APRIL", "SEMARANG", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["6.", "JAKARTA", "1 - 7 JANUARI", "SEMARANG", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["6.", "JAKARTA", "8 - 15 FEBRUARI", "SEMARANG", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["6.", "JAKARTA", "16 - 23 MARET", "SEMARANG", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["6.", "JAKARTA", "24 - 30 APRIL", "SEMARANG", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["7.", "JAKARTA", "1 -7 JANUARI", "SURABAYA", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["7.", "JAKARTA", "8 - 15 FEBRUARI", "SURABAYA", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["7.", "JAKARTA", "16 - 23 MARET", "SURABAYA", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["7.", "JAKARTA", "24 - 30 APRIL", "SURABAYA", "EKONOMI", "06.00 - 12.00 - 18.00"])
table.add_row(["8.", "JAKARTA", "1 - 7 JANUARI", "SURABAYA", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["8.", "JAKARTA", "8 - 15 FEBRUARI", "SURABAYA", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["8.", "JAKARTA", "16 - 23 MARET", "SURABAYA", "BISNIS", "06.00 - 12.00 - 18.00"])
table.add_row(["8.", "JAKARTA", "24 - 30 APRIL", "SURABAYA", "BISNIS", "06.00 - 12.00 - 18.00"])

print("------------------SELAMAT DATANG DI GO BUS-------------------")
pembeli = input("Nama Anda : ")
hp = int(input("No Hp :"))
email = input("Email :")

def tiket() :
  global total
  global jumlah
  global bus

  print("\n----------------- HALAMAN UTAMA -----------------")
  print("1. LIHAT JADWAL KEBERANGKATAN BUS")
  print("2. PEMESANAN TIKET GO BUS")
  menu = int(input("Ada yang bisa kami bantu? : "))

  if menu==1 : 
    print(table)
  elif menu==2 :
    print("1. KELAS EKONOMI")
    print("2. KELAS BISNIS")
    kelas = int(input("Silahkan pilih kelas : ")) 

    if kelas==1 :
      print("1. Jakarta Bandung - 06.00 - Rp. 70.000,-")
      print("2. Jakarta Bandung - 12.00 - Rp. 75.000,-")
      print("3. Jakarta Bandung - 18.00 - Rp. 75.000,-")
      print("4. Jakarta Semarang - 06.00 - Rp. 150.000,-")
      print("5. Jakarta Semarang - 12.00 - Rp. 165.000,-")
      print("6. Jakarta Semarang - 18.00 - Rp. 165.000,-")
      print("7. Jakarta Yogyakarta - 06.00 - Rp. 180.000,-")
      print("8. Jakarta Yogyakarta - 12.00 - Rp. 200.000,-")
      print("9. Jakarta Yogyakarta - 18.00 - Rp. 200.000,-")
      print("10. Jakarta Surabaya - 06.00 - Rp. 280.000,-")
      print("11. Jakarta Surabaya - 12.00 - Rp. 310.000,-")
      print("12. Jakarta Surabaya - 18.00 - Rp. 310.000,-")
      nomor = int(input("Jadi beli tiket kemana? : "))
      jumlah = int(input("Berapa tiket? : "))
      
      if nomor==1 :
        total = jumlah*70000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - BDG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==2 :
        total = jumlah*75000        
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - BDG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==3 :
        total = jumlah*75000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - BDG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==4 :
        total = jumlah*150000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SMG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==5 :
        total = jumlah*165000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SMG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==6 :
        total = jumlah*165000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SMG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==7 :
        total = jumlah*180000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - YK")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==8 :
        total = jumlah*200000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - YK")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==9 :
        total = jumlah*200000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - YK")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==10 :
        total = jumlah*280000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SBY")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==11 :
        total = jumlah*310000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SBY")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==12 :
        total = jumlah*310000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SBY")
        
        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      else :
        print("Pilihan tidak tersedia")
    
    elif kelas==2 :
      print("1. Jakarta Bandung - 06.00 - Rp. 150.000,-")
      print("2. Jakarta Bandung - 12.00 - Rp. 175.000,-")
      print("3. Jakarta Bandung - 18.00 - Rp. 175.000,-")
      print("4. Jakarta Semarang - 06.00 - Rp. 250.000,-")
      print("5. Jakarta Semarang - 12.00 - Rp. 300.000,-")
      print("6. Jakarta Semarang - 18.00 - Rp. 300.000,-")
      print("7. Jakarta Yogyakarta - 06.00 - Rp. 350.000,-")
      print("8. Jakarta Yogyakarta - 12.00 - Rp. 400.000,-")
      print("9. Jakarta Yogyakarta - 18.00 - Rp. 400.000,-")
      print("10. Jakarta Surabaya - 06.00 - Rp. 420.000,-")
      print("11. Jakarta Surabaya - 12.00 - Rp. 475.000,-")
      print("12. Jakarta Surabaya - 18.00 - Rp. 475.000,-")
      nomor = int(input("Jadi beli tiket kemana? : "))
      jumlah = int(input("Berapa tiket? : "))
      
      if nomor==1 :
        total = jumlah*150000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - BDG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==2 :
        total = jumlah*175000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - BDG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==3 :
        total = jumlah*175000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - BDG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==4 :
        total = jumlah*250000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SMG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==5 :
        total = jumlah*300000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SMG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==6 :
        total = jumlah*300000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SMG")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==7 :
        total = jumlah*350000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - YK")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==8 :
        total = jumlah*400000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - YK")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==9 :
        total = jumlah*400000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - YK")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==10 :
        total = jumlah*420000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SBY")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==11 :
        total = jumlah*475000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SBY")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================")
      elif nomor==12 :
        total = jumlah*475000
        print(jumlah, " tiket = Rp.", total)
        bus = ("JKT - SBY")

        print("\nTotal yang harus dibayar : Rp.", total)
        uang = int(input("Uang Tunai Pembeli : Rp "))
        kembalian = int(uang - total)
        print("Kembalian :", kembalian)

        print("==================================================")
        print("========== BUKTI PEMBELIAN TIKET GO BUS ==========")
        print("==================================================")
        print("Pembelian atas nama\t:", pembeli)
        print("No Handpone\t:", hp)
        print("Email\t\t:", email)
        print("Pembelian\t:", jumlah, "tiket", bus, "Rp.", total,)
        print("Dibayar\t\t: Rp", uang)
        print("Kembalian\t: Rp", kembalian)
        print("===================TERIMA KASIH===================")
        print("==================================================")
        print("==================================================") 

      else :
        print("Pilihan tidak tersedia")
    
    else :
      print("Pilihan tidak tersedia")

  else :
    print("Pilihan tidak tersedia")

tiket()

12